//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiverWhisperer.Onkyo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReceiverWhisperer.Onkyo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Muted.
        /// </summary>
        internal static string AMT00 {
            get {
                return ResourceManager.GetString("AMT00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        internal static string AMT01 {
            get {
                return ResourceManager.GetString("AMT01", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap brandlogo {
            get {
                object obj = ResourceManager.GetObject("brandlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input: .
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening Mode.
        /// </summary>
        internal static string ListeningMode {
            get {
                return ResourceManager.GetString("ListeningMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        internal static string LMD00 {
            get {
                return ResourceManager.GetString("LMD00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        internal static string LMD01 {
            get {
                return ResourceManager.GetString("LMD01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround.
        /// </summary>
        internal static string LMD02 {
            get {
                return ResourceManager.GetString("LMD02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        internal static string LMD03 {
            get {
                return ResourceManager.GetString("LMD03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THX.
        /// </summary>
        internal static string LMD04 {
            get {
                return ResourceManager.GetString("LMD04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string LMD05 {
            get {
                return ResourceManager.GetString("LMD05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical.
        /// </summary>
        internal static string LMD06 {
            get {
                return ResourceManager.GetString("LMD06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestra.
        /// </summary>
        internal static string LMD08 {
            get {
                return ResourceManager.GetString("LMD08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplugged.
        /// </summary>
        internal static string LMD09 {
            get {
                return ResourceManager.GetString("LMD09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio Mix.
        /// </summary>
        internal static string LMD0A {
            get {
                return ResourceManager.GetString("LMD0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Logic.
        /// </summary>
        internal static string LMD0B {
            get {
                return ResourceManager.GetString("LMD0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Channel Stereo.
        /// </summary>
        internal static string LMD0C {
            get {
                return ResourceManager.GetString("LMD0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theater Dimensional.
        /// </summary>
        internal static string LMD0D {
            get {
                return ResourceManager.GetString("LMD0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced.
        /// </summary>
        internal static string LMD0E {
            get {
                return ResourceManager.GetString("LMD0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string LMD0F {
            get {
                return ResourceManager.GetString("LMD0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure Audio.
        /// </summary>
        internal static string LMD11 {
            get {
                return ResourceManager.GetString("LMD11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplex.
        /// </summary>
        internal static string LMD12 {
            get {
                return ResourceManager.GetString("LMD12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Mono.
        /// </summary>
        internal static string LMD13 {
            get {
                return ResourceManager.GetString("LMD13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolby Virtual.
        /// </summary>
        internal static string LMD14 {
            get {
                return ResourceManager.GetString("LMD14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS Surround Sensation.
        /// </summary>
        internal static string LMD15 {
            get {
                return ResourceManager.GetString("LMD15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audyssey DSX.
        /// </summary>
        internal static string LMD16 {
            get {
                return ResourceManager.GetString("LMD16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole House Mode.
        /// </summary>
        internal static string LMD1F {
            get {
                return ResourceManager.GetString("LMD1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string LMD23 {
            get {
                return ResourceManager.GetString("LMD23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string LMD25 {
            get {
                return ResourceManager.GetString("LMD25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string LMD26 {
            get {
                return ResourceManager.GetString("LMD26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string LMD2E {
            get {
                return ResourceManager.GetString("LMD2E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.1 Channel Surround / Straight Decode.
        /// </summary>
        internal static string LMD40 {
            get {
                return ResourceManager.GetString("LMD40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolby EX/DTS ES.
        /// </summary>
        internal static string LMD41 {
            get {
                return ResourceManager.GetString("LMD41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THX Cinema.
        /// </summary>
        internal static string LMD42 {
            get {
                return ResourceManager.GetString("LMD42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THX Surround EX.
        /// </summary>
        internal static string LMD43 {
            get {
                return ResourceManager.GetString("LMD43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THX Music.
        /// </summary>
        internal static string LMD44 {
            get {
                return ResourceManager.GetString("LMD44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THX Games.
        /// </summary>
        internal static string LMD45 {
            get {
                return ResourceManager.GetString("LMD45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THX U2/S2/I/S Cinema/Cinema 2.
        /// </summary>
        internal static string LMD50 {
            get {
                return ResourceManager.GetString("LMD50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THX Music Mode.
        /// </summary>
        internal static string LMD51 {
            get {
                return ResourceManager.GetString("LMD51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THX Games Mode.
        /// </summary>
        internal static string LMD52 {
            get {
                return ResourceManager.GetString("LMD52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLII/PLIIx Movie.
        /// </summary>
        internal static string LMD80 {
            get {
                return ResourceManager.GetString("LMD80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLII/PLIIx Music.
        /// </summary>
        internal static string LMD81 {
            get {
                return ResourceManager.GetString("LMD81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neo:6 Cinema/Neo:X Cinema.
        /// </summary>
        internal static string LMD82 {
            get {
                return ResourceManager.GetString("LMD82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neo:6 Music/Neo:X Music.
        /// </summary>
        internal static string LMD83 {
            get {
                return ResourceManager.GetString("LMD83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLII/PLIIx THX Cinema.
        /// </summary>
        internal static string LMD84 {
            get {
                return ResourceManager.GetString("LMD84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neo:6/Neo:X THX Cinema.
        /// </summary>
        internal static string LMD85 {
            get {
                return ResourceManager.GetString("LMD85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLII/PLIIx Game.
        /// </summary>
        internal static string LMD86 {
            get {
                return ResourceManager.GetString("LMD86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLIIz Height.
        /// </summary>
        internal static string LMD90 {
            get {
                return ResourceManager.GetString("LMD90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Off.
        /// </summary>
        internal static string PWR00 {
            get {
                return ResourceManager.GetString("PWR00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On.
        /// </summary>
        internal static string PWR01 {
            get {
                return ResourceManager.GetString("PWR01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable / Satellite.
        /// </summary>
        internal static string SLI01 {
            get {
                return ResourceManager.GetString("SLI01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string SLI02 {
            get {
                return ResourceManager.GetString("SLI02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxillary 1.
        /// </summary>
        internal static string SLI03 {
            get {
                return ResourceManager.GetString("SLI03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxillary 2.
        /// </summary>
        internal static string SLI04 {
            get {
                return ResourceManager.GetString("SLI04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string SLI05 {
            get {
                return ResourceManager.GetString("SLI05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra 1.
        /// </summary>
        internal static string SLI07 {
            get {
                return ResourceManager.GetString("SLI07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra 2.
        /// </summary>
        internal static string SLI08 {
            get {
                return ResourceManager.GetString("SLI08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blu-Ray / DVD.
        /// </summary>
        internal static string SLI10 {
            get {
                return ResourceManager.GetString("SLI10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD.
        /// </summary>
        internal static string SLI23 {
            get {
                return ResourceManager.GetString("SLI23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM Radio.
        /// </summary>
        internal static string SLI24 {
            get {
                return ResourceManager.GetString("SLI24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM Radio.
        /// </summary>
        internal static string SLI25 {
            get {
                return ResourceManager.GetString("SLI25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuner.
        /// </summary>
        internal static string SLI26 {
            get {
                return ResourceManager.GetString("SLI26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLNA.
        /// </summary>
        internal static string SLI27 {
            get {
                return ResourceManager.GetString("SLI27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Radio.
        /// </summary>
        internal static string SLI28 {
            get {
                return ResourceManager.GetString("SLI28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB (Front).
        /// </summary>
        internal static string SLI29 {
            get {
                return ResourceManager.GetString("SLI29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB (Rear).
        /// </summary>
        internal static string SLI2A {
            get {
                return ResourceManager.GetString("SLI2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string SLI2B {
            get {
                return ResourceManager.GetString("SLI2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Level: .
        /// </summary>
        internal static string VolumeLevel {
            get {
                return ResourceManager.GetString("VolumeLevel", resourceCulture);
            }
        }
    }
}
